"""
response_generator.py

Purpose
-------
Generates the final natural language response
using the configured Large Language Model.

This class NEVER:

- Builds prompts
- Retrieves documents
- Runs ML predictions
- Calculates SHAP

It simply forwards a completed prompt
to the LLM service and returns the response.

Pipeline
--------

Completed Prompt
        │
        ▼
Response Generator
        │
        ▼
LLM Service
        │
        ▼
Configured LLM
        │
        ▼
Generated Response
"""



from rag.LLM.gemini_service import GeminiService


class ResponseGenerator:

    def __init__(self):

        self.llm = GeminiService()

    def generate(
        self,
        prompt: str,
    ) -> str:

        return self.llm.generate(prompt)


# ==========================================================
# Testing
# ==========================================================

if __name__ == "__main__":

    generator = ResponseGenerator()

    prompt = """
You are a Senior Credit Risk Analyst at Stratum Capital Bank.

Your task is to explain a loan decision generated by an AI-assisted credit risk assessment system.

The explanation will be shown to loan officers and internal banking professionals.

Use ONLY the information provided below.

Never invent applicant information.

Never invent banking policies.

Never invent model outputs.

Never mention LightGBM, SHAP implementation details, embeddings, retrieval systems, or internal AI architecture.

=========================================================
USER QUESTION
=========================================================

Why was this applicant's loan rejected?

=========================================================
APPLICANT PROFILE
=========================================================

Loan Amount:
12,000

Interest Rate:
13.33%

Loan Term:
36 Months

Annual Income:
71,000

Debt-to-Income Ratio:
12%

Sub Grade:
B3

Purpose:
Debt Consolidation

Employment Length:
7 Years

Home Ownership:
Mortgage

=========================================================
MODEL PREDICTION
=========================================================

Decision

Rejected

Repayment Probability

27.08%

Default Probability

72.92%

=========================================================
TOP MODEL FACTORS (SHAP)
=========================================================

1. Interest Rate
   Strong Negative Influence

2. Annual Income
   Positive Influence

3. Loan Amount
   Negative Influence

4. Debt-to-Income Ratio
   Moderate Negative Influence

5. Sub Grade
   Negative Influence

=========================================================
RETRIEVED BANK POLICY EVIDENCE
=========================================================

Evidence 1

Chapter 5 – Loan Policy Manual

The Debt-to-Income ratio is a key affordability metric used during underwriting. Applications with elevated repayment obligations relative to verified income require additional review because repayment capacity may become insufficient under financial stress.

---------------------------------------------------------

Evidence 2

Chapter 15 – Lending Decision Handbook

High requested loan amounts combined with elevated borrowing costs increase repayment risk, even when an applicant demonstrates acceptable credit history. Credit quality alone should not offset affordability concerns.

---------------------------------------------------------

Evidence 3

Chapter 14 – Credit Rating Framework

Income contributes to repayment capacity assessment and interacts with Debt-to-Income calculations. Two applicants with similar credit ratings may receive different lending decisions when affordability differs.

=========================================================
YOUR TASK
=========================================================

Produce a professional credit decision explanation.

Your explanation should:

1. Answer the user's question directly.

2. Explain why the applicant was rejected.

3. Connect the model's important factors with the retrieved banking policy.

4. Explain how affordability influenced the decision.

5. Explain why annual income helped the application but was insufficient to offset the remaining risks.

6. Discuss how the requested loan amount and interest rate contributed to the decision.

7. Mention any remaining financial risks.

8. Keep the explanation factual, professional, and suitable for banking staff.

=========================================================
RULES
=========================================================

- Use only the supplied information.

- Do not invent applicant information.

- Do not invent banking policies.

- Do not quote policies verbatim unless provided.

- Do not mention internal AI implementation.

- Present the explanation in clear professional language.

- Avoid bullet points unless necessary.

- Keep the response between 250 and 450 words.
"""

    response = generator.generate(prompt)

    print("=" * 80)
    print("LLM RESPONSE")
    print("=" * 80)
    print(response)


    